=== artoonie/rcvformats/rcvformats/jsonschemas/opavote_v1_1.schema.json
{
  "$id": "https://github.com/artoonie/rcvformats/blob/main/rcvformats/jsonschemas/opavote.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Opavote JSON Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "candidates": {
      "type": "array",
      "description": "List of all candidates",
      "items": {
        "type": "string",
        "description": "Candidate name"
      }
    },
    "method": {
      "type": "string",
      "description": "RCV tabulation method"
    },
    "n_seats": {
      "type": "number",
      "description": "Number of seats to fill",
      "minimum": 1
    },
    "n_valid_votes": {
      "type": "number",
      "description": "Number of valid ballots",
      "minimum": 1
    },
    "n_votes": {
      "type": "number",
      "description": "Total ballots, including invalid ballots",
      "minimum": 1
    },
    "options": {
      "type": "array",
      "description": "The opavote configuration options",
      "items": {
        "type": "array",
        "description": "Info about one configuration type",
        "items": [
          {
            "type": "string",
            "description": "Name of the configuration option"
          },
          {
            "type": ["string", "number"],
            "description": "What the option is set to"
          }
        ]
      }
    },
    "precision": {
      "type": "number",
      "description": "To be figured out - I'm not sure"
    },
    "rounds": {
      "type": "array",
      "description": "Description of what happens in each round",
      "items": {
        "type": "object",
        "description": "A single round",
        "additionalProperties": false,
        "properties": {
          "action": {
            "type": "object",
            "description": "Text to describe what happened in this round",
            "additionalProperties": false,
            "properties": {
              "candidates": {
                "$ref": "#/$defs/candidate-indices",
                "description": "Which candidates are eliminated or elected"
              },
              "desc": {
                "type": "string",
                "description": "Human-readable description of the round"
              },
              "type": {
                "type": "string",
                "description": "The action taken",
                "enum": ["first", "eliminate", "surplus"]
              }
            },
            "required": [
              "desc",
              "type"
            ]
          },
          "continuing": {
            "$ref": "#/$defs/candidate-indices",
            "description": "Which candidates are continuing"
          },
          "thresh": {
            "type": "number",
            "description": "The threshold for this round, optionally",
            "minimum": 0
          },
          "surplus": {
            "type": "number",
            "description": "The number of surplus votes this round",
            "minimum": 0
          },
          "count": {
            "type": "array",
            "description": "The number of votes each candidate currently has",
            "items": {
              "type": "number",
              "minimum": 0
            }
          },
          "exhausted": {
            "type": "number",
            "description": "Number of exhausted ballots"
          },
          "losers": {
            "$ref": "#/$defs/candidate-indices",
            "description": "Which candidates have lost so far - cumulative"
          },
          "msg": {
            "type": "string",
            "description": "Human-readable summary of the round"
          },
          "n": {
            "type": "number",
            "description": "Current round index, 1-indexed",
            "minimum": 1
          },
          "winners": {
            "$ref": "#/$defs/candidate-indices",
            "description": "Which candidates were elected"
          }
        },
        "required": [
          "count",
          "losers",
          "winners"
        ]
      }
    },
    "tie_breaks": {
      "type": "array",
      "description": "If any tie-breaking happened, how did it happen?",
      "items": {
        "type": "array",
        "description": "A round's tie-breaking data",
        "items": [
          {
            "type": "number",
            "description": "Which round? 1-indexed",
            "minimum": 1
          },
          {
            "$ref": "#/$defs/candidate-indices",
            "description": "Which candidates is the tie-break between"
          },
          {
            "$ref": "#/$defs/candidate-indices",
            "description": "Which candidate(s) won the tie-break"
          }
        ]
      }
    },
    "title": {
      "type": "string",
      "description": "Title of the election"
    },
    "version": {
      "type": "string",
      "description": "Version of this schema - must be 1.0",
      "const": "1.0"
    },
    "winners": {
      "$ref": "#/$defs/candidate-indices",
      "description": "List of all winners"
    },
    "withdrawn": {
      "$ref": "#/$defs/candidate-indices",
      "description": "Which candidates withdrew before the election began"
    }
  },
  "required": [
    "candidates",
    "rounds",
    "title",
    "version"
  ],
  "$defs": {
    "candidate-indices": {
      "type": "array",
      "items": {
        "type": "number",
        "minimum": 0
      }
    }
  }
}

=== artoonie/rcvformats/testdata/inputs/opavote11/2022-example.json
{"n_seats": 2, "n_votes": 24, "title": "40th LD Resolutions", "precision": 6, "withdrawn": [], "method": "Fractional Transfer STV", "version": "1.0", "candidates": ["BBB", "Implement", "ADHD", "Tax Credit"], "winners": [0, 1], "tie_breaks": [], "options": [["prec", 6], ["thresholdFormula", "Droop"], ["dynamicThreshold", "Dynamic"], ["fractionalThreshold", "Fractional"], ["delayedTransfer", "On"], ["batchElimination", "Zero"], ["weakTieBreakMethod", "Backward"], ["removeOvervotes", "Skip"], ["removeUndervotes", "Skip"]], "rounds": [{"count": [13000000, 7000000, 2000000, 2000000], "surplus": 4999999, "exhausted": 0, "continuing": [1, 2, 3], "n": 1, "msg": "Count of first choices. Candidate BBB has reached the threshold and is elected. Candidates have surplus votes so surplus votes will be transferred for the next round. ", "winners": [0], "losers": [], "action": {"type": "first", "desc": "Count of first choices. "}, "thresh": 8000001}, {"count": [8000001, 9692305, 3538460, 2769230], "surplus": 1692306, "exhausted": 4, "continuing": [2, 3], "n": 2, "msg": "Count after transferring surplus votes from BBB with a transfer value of 4.999999/13.000000. Candidate Implement has reached the threshold and is elected. ", "winners": [0, 1], "losers": [], "action": {"type": "surplus", "candidates": [0], "desc": ""}, "thresh": 7999999}], "n_valid_votes": 24}
